Create an option to run a DNS query before the STUN/TURN tests
nimbleape/iceperf-agent pull request #16
Opened 2024-12-09 10:29 UTC by Megzo

### This PR adds support to run a DNS query before the actual STUN and TURN measurements are started to measure DNS query time and cache the IP of the STUN/TURN server

I noticed during my tests that sometimes the STUN latency measurement gives a quite high result comapred to the RTT between the client and the server. I double check our STUN server ([using this tool](https://github.com/renandincer/stun-timing)) and I figured out that this is not caused by the server itself, but actually the DNS query time of our domain is a bit slow. 

The other intresting fact is that this DNS query time usually only affects the first measurement (tipically STUN latency) and the subsequent tests to the same server (e.g. TURN tests) will have the domain cached locally (e.g. due to `systemd-resolved`) so they don't contain this extra step.

Therefore, I figured that I add a new option to `iceperf-agent` which can run a DNS query befor starting the actual STUN/TURN tests to populate the DNS cache. It works as follows:
 - there is a new option in the config called `dns_query_enabled` on the provider config which can be set to `true` to trigger this behaviour
  - if the option is set to `false` or omitted, the separate DNS query won't be executed, maintining backward compatibility with old config files
   - the result of the DNS query is also printed out after the test as follows (you can see that only the first DNS query took a long time, subsequent DNS queries are fast due to local cache):
 ```
Provider  Scheme  Protocol  Time to candidate  Max Throughput  TURN Transfer Latency
stunner   stun    dns       24                 0               0
stunner   stun    udp       22                 0               0
stunner   turn    dns       4                  0               0
stunner   turn    udp       38                 0               16
 ```
 
Note: I'm not sure if this is the proper output format (e.g. `scheme=stun, protocol=dns` does not make too much sense, but this way we can see which measurement the DNS query belonged to). Let me know if I should change the output format.
 
PS: It's also fair to say that the DNS query is also part of the ICE process, so it make sense to include this in the actual STUN/TURN measurements (e.g. if you have a slow DNS service then the whole ICE process will be slowed down), but seperating the DNS from the actual STUN/TURN measurement can also point the user to which part of the system is actually causing the delay (like in my case).

2024-12-19 10:01 UTC, danjenkins commented
Thanks for this @Megzo ! We'll try and get this tested and merged in this week!

2024-12-19 16:46 UTC, marcovidonis requested changes
Hey @Megzo, thanks for your PR! I've had a look at the code and ran some tests myself and I do see the impact of the DNS step.

What do you think about adding a "main switch" for the DNS query feature, so we can enable or disable it for all providers at once? We think it would make sense to have the same set of tests during a whole test run. The switch could then be overridden in the config at the provider level (for example, it's ON for all except this provider, and vice versa).

Another thing we'd like to investigate is clearing the DNS cache before each query. As it stands, if we're sending this data for collection, we'll have unreliable data for all the times we got the DNS from cache and it results in a response time of 1 ms.

As for the naming convention, I believe `scheme: stun, protocol: dns` is clear enough for data collection purposes, even though it might not be technically correct.

2025-01-16 16:58 UTC, danjenkins commented
@Megzo did you see the reply from @marcovidonis ?

2025-01-20 12:45 UTC, Megzo commented
Hi everyone,

Sorry, I completly missed these comments.
Let me run some test, and get back with the results during this week.

2025-01-27 16:32 UTC, Megzo commented
Hi everyone,

So I did some extensive measurements in our env, and turned out this prefetch DNS does not really add up too much difference, just as @marcovidonis said.

This sent me down to some other paths (e.g. using the `/etc/hosts` file for static IP setting to bypass DNS in comparision measurements), and I also added support for the STUNner auth service (see my other pull request).

To that end, I'll close this PR, no need for merging.

If someone else having issues with DNS being unpredictable, you could potetially revisit this in the future.

2025-01-27 16:32 UTC, closed without merging

2025-01-27 17:01 UTC, danjenkins commented
Thanks!